import {useEffect,useState} from 'react';
import {CheckCircle2, Circle, AlertTriangle, Loader2, XCircle, Database, Download, ChevronLeft, ChevronRight, X} from 'lucide-react';
import {api,fmt, type Row,type Dataset} from './api';

export function Status({value}:{value:string}){const Icon=['successful','passed','proposed'].includes(value)?CheckCircle2:['failed'].includes(value)?XCircle:value==='running'?Loader2:value==='warning'?AlertTriangle:Circle;return <span className={'status '+value}><Icon size={13} className={value==='running'?'spin':''}/>{value.replace('_',' ')}</span>}
export function Empty({title,children}:{title:string;children?:React.ReactNode}){return <div className="empty"><Database size={28}/><h3>{title}</h3><p>{children}</p></div>}
export function Modal({title,children,onClose,wide=false}:{title:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler)},[onClose]);return <div className="overlay" onClick={onClose}><section className={'modal '+(wide?'wide':'')} role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><header><h2>{title}</h2><button aria-label="Close dialog" className="icon-button" onClick={onClose}><X size={20}/></button></header>{children}</section></div>}
export function Table({rows,highlight=-1}:{rows:Row[];highlight?:number}){if(!rows.length)return <p className="muted table-empty">No rows to display.</p>;const cols=Object.keys(rows[0]);return <div className="table-scroll"><table><thead><tr><th className="row-index">#</th>{cols.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className={i===highlight?'highlight':''}><td className="row-index">{i+1}</td>{cols.map(c=><td key={c} className={typeof row[c]==='number'?'numeric':''} title={fmt(row[c])}>{fmt(row[c])}</td>)}</tr>)}</tbody></table></div>}
export function DataPreview({wid,did,highlight=-1}:{wid:string;did:string;highlight?:number}){const [data,setData]=useState<Dataset|null>(null);const [offset,setOffset]=useState(0);const [tab,setTab]=useState('data');const [error,setError]=useState('');useEffect(()=>{setOffset(0);setData(null)},[did]);useEffect(()=>{let active=true;setError('');api<Dataset>(`/workspaces/${wid}/datasets/${did}?offset=${offset}`).then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[wid,did,offset]);return <div className="preview">{error&&<p role="alert" className="error">{error}</p>}{!data?<div className="loading"><Loader2 className="spin" size={18}/> Loading dataset…</div>:<><div className="preview-head"><div><strong>{data.name}</strong><span className="muted">{data.rows.toLocaleString()} rows · {data.schema.length} columns</span></div><a className="icon-button" href={`/api/workspaces/${wid}/datasets/${did}/download`} title="Download Parquet"><Download size={16}/></a></div><div className="tabs small">{['data','schema','profile'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='data'?<><Table rows={data.data} highlight={highlight}/><footer className="pagination"><span>{data.rows?offset+1:0}–{Math.min(offset+50,data.rows)} of {data.rows} rows</span><div><button aria-label="Previous page" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}><ChevronLeft size={16}/></button><button aria-label="Next page" disabled={offset+50>=data.rows} onClick={()=>setOffset(offset+50)}><ChevronRight size={16}/></button></div></footer></>:tab==='schema'?<Table rows={data.schema as unknown as Row[]}/>:<Table rows={data.profile.columns.map(c=>({column:c.name,type:c.type,missing:c.missing,distinct:c.distinct,min:c.min,max:c.max,mean:c.mean}))}/>}</>}</div>}
